#!/usr/bin/env node
// Allocates free CLIENT_PORT / SERVER_PORT for this worktree and writes them to .env.local.
// Idempotent: reuses an existing .env.local if its ports are still free.
// Avoids ports already claimed by sibling worktrees' .env.local files (git worktree list).
// Usage: node scripts/ports.mjs [--force]
import fs from 'node:fs';
import net from 'node:net';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { DEFAULTS, envFilePath, parseEnvFile } from './env.mjs';

const force = process.argv.includes('--force');
const cwd = process.cwd();
const file = envFilePath(cwd);

function canBind(port, host) {
  return new Promise((resolve) => {
    const srv = net.createServer();
    srv.once('error', () => resolve(false));
    srv.listen(host ? { port, host } : { port }, () => srv.close(() => resolve(true)));
  });
}

// Servers may bind IPv4 only (Fastify), IPv6 only (Vite on macOS), or both — probe all.
async function isFree(port) {
  for (const host of ['127.0.0.1', '::1', undefined]) {
    if (!(await canBind(port, host))) return false;
  }
  return true;
}

function claimedBySiblings() {
  const claimed = new Set();
  try {
    const out = execSync('git worktree list --porcelain', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    });
    for (const line of out.split('\n')) {
      if (!line.startsWith('worktree ')) continue;
      const dir = line.slice('worktree '.length);
      if (path.resolve(dir) === path.resolve(cwd)) continue;
      const env = parseEnvFile(envFilePath(dir));
      for (const k of Object.keys(DEFAULTS)) if (env[k]) claimed.add(Number(env[k]));
    }
  } catch {
    /* not a git repo or git missing: nothing to avoid */
  }
  return claimed;
}

async function allocate(start, taken) {
  for (let p = start; p < start + 1000; p++) {
    if (taken.has(p)) continue;
    if (await isFree(p)) return p;
  }
  throw new Error(`No free port found starting at ${start}`);
}

async function main() {
  const existing = parseEnvFile(file);
  const taken = claimedBySiblings();
  const result = {};

  for (const [key, def] of Object.entries(DEFAULTS)) {
    const prev = Number(existing[key]);
    // Reuse a previously allocated port if still usable (or if a server is already bound to it
    // by this worktree we can't tell — so only reallocate when --force or the port is claimed by a sibling).
    if (!force && prev && !taken.has(prev) && (await isFree(prev))) {
      result[key] = prev;
    } else if (!force && prev && !taken.has(prev)) {
      // Not free, but not claimed elsewhere: most likely our own running dev server. Keep it.
      result[key] = prev;
    } else {
      result[key] = await allocate(def, taken);
    }
    taken.add(result[key]);
  }

  const body = Object.entries(result)
    .map(([k, v]) => `${k}=${v}`)
    .join('\n');
  fs.writeFileSync(file, `# Generated by scripts/ports.mjs — per-worktree, gitignored\n${body}\n`);

  for (const [k, v] of Object.entries(result)) console.log(`${k}=${v}`);
  console.log(`(written to ${file})`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
